connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=${ENV:ICEBERG_REST_URI}
iceberg.rest-catalog.warehouse=s3://${ENV:MINIO_BUCKET}/

# Native S3 filesystem
fs.native-s3.enabled=true
s3.endpoint=${ENV:MINIO_ENDPOINT}
s3.region=${ENV:AWS_REGION}
s3.aws-access-key=${ENV:AWS_ACCESS_KEY_ID}
s3.aws-secret-key=${ENV:AWS_SECRET_ACCESS_KEY}
s3.path-style-access=true
